### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by LJHG** [hhhhfff/IsaacAnimation2Gif#1]
Can you tell me which py file to run to get the gif?

**Comment by HHHFFei** [comment]
’IsaacAnimationEditor.py' in ‘py‘ folder .You can read README to get more informations.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhhhfff/IsaacAnimation2Gif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月19日(星期一) 下午3:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hhhhfff/IsaacAnimation2Gif] How to run (Issue #1)





 
Can you tell me which py file to run to get the gif?

**Comment by LJHG** [comment]
Thanks!
